config/routes.rb
Atlrug4::Application.routes.draw do

  root :to => "content#index"

  get '/meetings' => 'content#meetings'
  get '/videos' => 'content#videos'
  get '/hire' => 'content#hire'
  get '/learn' => 'content#learn'
  get '/job' => 'content#job'

  resources :talks, :only => [:new, :create] do
    get :approve, :on => :collection
    put :accept, :on => :member
  end
  
  resources :jobs, :only => [:index, :new, :create] do
    get :view, :on => :member
    get :delete, :on => :member
  end
  
  resources :resumes, :only => [:index, :new, :create] do
    get :view, :on => :member
    get :delete, :on => :member
  end

  get '/auth/:provider/callback', :to => 'sessions#create'
  get '/login' => redirect('/auth/github'), :as => :login
  get '/log_out' => 'sessions#destroy', :as => :log_out

end

app/models/talk.rb
class Talk < ActiveRecord::Base
  validates :title, :email, :duration, :description, :presence => true
  validates :duration, :numericality => { :greater_than => 0,
    :only_integer => true }
  validates :email, :format => /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\z/i

  scope :pending, -> { where(:approved => false) }
end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  def new
    @talk = Talk.new
  end

  def create
    @talk = Talk.new(talk_params)
    if @talk.save
      redirect_to root_url,
        :notice => "Your talk has been submitted for review!"
    else
      flash[:alert] = "Your proposal couldn't be submitted!"
      render :new
    end
  end

  def approve
    @talks = Talk.pending.map { |talk| TalkDecorator.new(talk) }
  end

  def accept
    @talks = Talk.pending.map { |talk| TalkDecorator.new(talk) }
  end

private
  def talk_params
    params.require(:talk).permit(
      :title, :email, :duration, :description, :twitter)
  end
end

app/helpers/talks_helper.rb
module TalksHelper
end

app/views/talks/accept.html.haml
#contact-us.container
  .row
    .col-md-12
      - model_class = Talk
      .page-header
        %h1 Accepted Talks - scheduled for next meetup
      %table.table.table-striped
        %thead
          %tr
            %th Title
            %th Description
            %th Duration
        %tbody
          - @talks.each do |talk|
            %tr
              %td= talk.title
              %td= talk.description
              %td= talk.duration

app/views/talks/approve.html.haml
#contact-us.container
  .row
    .col-md-12
      - model_class = Talk
      .page-header
        %h1 Approve Talks
      %table.table.table-striped
        %thead
          %tr
            %th Title
            %th Description
            %th Duration
        %tbody
          - @talks.each do |talk|
            %tr
              %td= talk.title
              %td= talk.description
              %td= talk.duration
              %td
                = link_to "Approve", accept_talk_path(talk), :method => :put, :class => "btn"

app/views/talks/new.html.haml
#talk.container
  .row
    .col-md-12
      - model_class = Talk
      %h1 Interested in speaking?
      %p Please fill out this form, and a group leader will get back to you as soon as possible.
  .row
    .col-md-7
      = simple_form_for @talk, :html => {:class => 'form-horizontal'} do |f|
        .fieldset.col-md-6
          %legend ATLRUG Talk Proposal
          - if flash[:alert]
            %p.alert.alert-danger
              %a.close{"data-dismiss" => "alert"}&times;
              = flash[:alert]

          = f.input :title, :input_html => {:class => 'form-control'}

          = f.input :description, :input_html => { :rows => 4, :class => 'form-control' }

          = f.input :duration, :label => "Duration (minutes)", :hint  => "Just estimate. Most talks are 15-30 minutes.", :input_html => { :step => 5, :min => 0, :class => 'form-control' }

          = f.input :email, :input_html => {:class => 'form-control'}
          = f.input :twitter, :wrapper => :prepend, :label => "* Twitter Username (@)" do
            = f.input_field :twitter, :class => 'form-control'

          .form-actions
            = f.button :submit, "Submit Proposal", :class => "btn-info btn-large"
    .col-md-5
      = image_tag "atl_meetup2.jpg", :alt => "Give a Talk", :class => "thumbnail"