config/routes.rb
Atlrug4::Application.routes.draw do

  root :to => "content#index"

  get '/meetings' => 'content#meetings'
  get '/videos' => 'content#videos'
  get '/hire' => 'content#hire'
  get '/learn' => 'content#learn'
  get '/job' => 'content#job'

  resources :talks, :only => [:new, :create] do
    get :approve, :on => :collection
    put :accept, :on => :member
  end
  
  resources :jobs, :only => [:index, :new, :create] do
    get :view, :on => :member
    get :delete, :on => :member
  end
  
  resources :resumes, :only => [:index, :new, :create] do
    get :view, :on => :member
    get :delete, :on => :member
  end

  get '/auth/:provider/callback', :to => 'sessions#create'
  get '/login' => redirect('/auth/github'), :as => :login
  get '/log_out' => 'sessions#destroy', :as => :log_out

end

app/views/layouts/_banner.html.haml
#banner-wrapper
	#banner
		.container
			.row
				.col-md-12
					.col-md-7
						%h1 Atlanta Ruby Users Group
					.col-md-7
						%h4 Meet with others interested in developing, promoting, fostering, strengthening, and improving the Ruby programming language and Ruby community.

app/views/layouts/_footer.html.haml
#sponsors.container
  .row
    .col-md-7
      %h4 <b>Platinum Sponsor
      %ul.platinum
        %li
          %a{:href => 'http://mandrill.com'} Mandrill
          – Transactional Email from MailChimp
        %li.sponsor-image
          %a{:href => 'http://mandrill.com'}
            =image_tag "mandrill.png", :alt => 'Mandrill'
    .col-md-5
      %h4 <b>Other Sponsors
      %ul.other
        %li
          %a{:href => 'http://rentpath.com/'} RentPath
          %span Provides Space for Emerald City Meetings
        %li
          %a{:href => 'http://www.bignerdranch.com'} Big Nerd Ranch
          %span Pays for Meetup Account Fees

app/views/layouts/_footerlinks.html.haml
#contact-us.container
  .row
    .col-md-6.col-md-offset-3
      %ul.nav
        %li.active
          %a{:href => "http://meetup.com/atlantaruby/"}
            %i.icon-group
            Meetup
        %li
          %a{:href => "http://twitter.com/atlrug"}
            %i.icon-twitter
            @atlrug
        %li
          %a{:href => "https://github.com/atlrug/atlrug4/wiki"}
            %i.icon-github
            Wiki
        %li
          %a{:href => "http://www.linkedin.com/groups/Atlanta-Ruby-Users-Group-106945/about"}
            %i.icon-linkedin-sign
            Linkedin
        %li
          %a{:href => "http://webchat.freenode.net/?channels=atlrug"}
            %i.icon-comments-alt
            IRC-Chat

app/views/layouts/_navbar.html.haml
#main-nav.navbar
  .navbar-inner
    .container
      %a{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :class => "btn navbar-btn"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar

      %a.logo{:href => root_url }
        =image_tag "ATLRUG_logo.png", :alt => 'Atlanta Ruby Logo'
      %div.navbar-collapse
        %ul.nav.navbar-nav.nav-links.navbar-left
          %li
            = link_to 'Go to Meetings', meetings_path
          -# %li
          -#   = link_to 'Find Presentations', videos_path
          %li
            = link_to 'Learn Ruby', '/learn'
        %ul.nav.navbar-nav.nav-links.navbar-right
          %li
            = link_to 'Find a Job', jobs_path
          %li
            = link_to 'Hire Someone', resumes_path
          -# %li
          -#  = link_to 'Give a Talk', new_talk_path
          -#%li.dropdown.admin-nav
          -#  %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
          -#    Admin
          -#    %b.caret
          -#  %ul.dropdown-menu
          -#    - if signed_in?
          -#      %li
          -#        %a{:href => approve_talks_path, :tabindex => "-1"} Approve Talks
          -#      %li
          -#        %a{:href => log_out_path, :method => :delete, :tabindex => "-1"} Log out
          -#    - else
          -#      %li
          -#        %a{:href => login_path, :tabindex => "-1"} Login

app/views/layouts/application.html.haml
%html
  %head
    %title Atlanta Ruby Users' Group

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = stylesheet_link_tag    "http://fonts.googleapis.com/css?family=Roboto+Slab:400,700"
    = stylesheet_link_tag    "//netdna.bootstrapcdn.com/font-awesome/3.1.1/css/font-awesome.css"
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tag

  %body
    = render 'layouts/navbar'
    #main= yield
    / #tweet
    /   %a{:href=>"http://twitter.com/atlrug", :class=> "twitter-follow-button", :'data-show-count'=> "false"} Follow @atlrug
    /   %script{:src=> "http://platform.twitter.com/widgets.js", :type=>"text/javascript"}
    / #sidebar

    #footer
      = render 'layouts/footer'
    #footer-links
      = render 'layouts/footerlinks'